name: Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Essa é a release para a versão `${{ github.ref_name }}`.
            - Adicione notas detalhadas aqui se quiser.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
